name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g cordova

    - name: Create App
      run: |
        cordova create myApp
        cd myApp
        cordova platform add android
    - name: Build APK
      run: |
        cd myApp
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: myApp/platforms/android/app/build/outputs/apk/debug/
